### ISSUE TITLE
No module named 'sounddevice'

### ISSUE THREAD

**Issue by IntrovertedFL** [ILikeAI/AlwaysReddy#2]
I'm using Pop!_OS 22.04 LTS, I followed instructions from the repo to install. I receive the below error when attempting to run. 

```
Traceback (most recent call last):
  File "/home/me/Documents/GitHub/AlwaysReddy/main.py", line 2, in <module>
    from audio_recorder import AudioRecorder
  File "/home/me/Documents/GitHub/AlwaysReddy/audio_recorder.py", line 1, in <module>
    import sounddevice as sd
ModuleNotFoundError: No module named 'sounddevice'
```

I installed apt package `libportaudio2` and when I used ```pip install sounddevice``` to install `sounddevice` I got the below response as if it was already installed:
```

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sounddevice in /home/me/.local/lib/python3.10/site-packages (0.4.6)
Requirement already satisfied: CFFI>=1.0 in /home/me/.local/lib/python3.10/site-packages (from sounddevice) (1.16.0)
Requirement already satisfied: pycparser in /home/me/.local/lib/python3.10/site-packages (from CFFI>=1.0->sounddevice) (2.21)
```

Any idea on how I can fix this issue?

**Comment by ILikeAI** [comment]
Did you manage to resolve this? I have not tested the repo on Linux yet, its possible some of the libraries are windows exclusive..

**Comment by IntrovertedFL** [comment]
I did not, I decided to wait to see if others posted with the same issues.

**Comment by ILikeAI** [comment]
I haven't tested on Linux yet so its possible it is a compatibility issue with one of the libraries
