### ISSUE TITLE
Not writing to clipboard

### ISSUE THREAD

**Issue by POD319** [ILikeAI/AlwaysReddy#24]
I rambled for a bit and ended my statement with "Could you put on my clipboard basically a summary of that question that I can post?", and the bot responded with a good summary, but did not try to put it on my clipboard.

Is there a specific trigger word I need in order for it to write to my clipboard? I did double tap space and saw that part worked prior to my inquiry.

Thanks for any help!

**Comment by ILikeAI** [comment]
Hey, yeah unfortunately AlwaysReddy does not fully understand its powers, sometimes it will put random stuff in my clipboard, sometimes it will forget how to use it. I'm hoping some prompt wizards can help with this (or even better, a custom finetune) 

In answer to your question, if you want AlwaysReddy to put something in the clipboard you just need to ask, if it doesn't do it the first time I cut it off and remind it that I want the contents in my clipboard. If it's being super dumb you can say something like "just put it between the clipboard sequences so I can paste it" 

Probably smaller models will struggle more with using the tools, I still mostly use anthropic sonnet
