### ISSUE TITLE
Near-real-time TTS 

### ISSUE THREAD

**Issue by sarutobiumon** [ILikeAI/AlwaysReddy#3]
Suggest using Piper for TTS since it is the only near-real-time TTS that is free/open-source.
Thanks for the great work!

https://www.youtube.com/watch?v=a7EVIgh_xkE
More on Piper including training:
https://www.youtube.com/@Natlamir/videos

**Comment by ILikeAI** [comment]
Never heard of it, thanks for sharing I'll check it out this week :)

**Comment by ILikeAI** [comment]
Integrated!
