### ISSUE TITLE
Setup.py fails on non-Debian Linux

### ISSUE THREAD

**Issue by Theo-codatte** [ILikeAI/AlwaysReddy#41]
Hi there,

When i'm trying to `python setup.py` i got this error on Arch Linux. This error will spawn on any Linux which do not use `apt-get`.

```
Error installing Linux dependencies: Command '['sudo', 'apt-get', 'install', '-y', 'xclip', 'ffmpeg', 'portaudio19-dev']' returned non-zero exit status 1.
```

Cheers

EDIT : this works on Arch Linuxes `subprocess.check_call(['sudo', 'pacman', '-Sy', 'xclip', 'ffmpeg', 'portaudio'])`

**Comment by ILikeAI** [comment]
Nice catch! I have only tested on debian so far. Once you changed this command did the rest of the set up process work?

**Comment by ILikeAI** [comment]
Im updating the setup file now, should be fixed in a couple min

**Comment by Theo-codatte** [comment]
Hello,

 cheers I will try it. 

Fun fact, I can setup some hotkeys with the GUI
But they are not working during AE usage.

Among others, I got some JACK error.

I m using whisperx + piper, logs to come !
