### ISSUE TITLE
Groq API?

### ISSUE THREAD

**Issue by jgbrwn** [ILikeAI/AlwaysReddy#52]
Just stumbled upon this project and haven’t tried yet, but my first thought is, this would be awesome if could utilize Groq API for the LLM component.  Currently the API is free and near instantaneous results.

https://groq.com

You can play around with it here and clicking the code button shows you the Python/curl API code examples:

https://console.groq.com/playground?model=llama3-70b-8192

**Comment by ILikeAI** [comment]
Great suggestion, id be keen to try this out. Should be very easy to integrate

**Comment by jgbrwn** [comment]
Very cool, if anything I figured you’d dig the speed of groq’s api/infra.
