### ISSUE TITLE
"Playing audio:" messages appear after the line has been spoken.

### ISSUE THREAD

**Issue by HAV0X1014** [ILikeAI/AlwaysReddy#66]
Currently, the Piper TTS spoken audio line prints its contents after the complete line is said. For example, when the line "Playing audio: Its lazy rhythm, a hypnotic beat" is printed, the line's contents have already been said. I'm unsure if this is the intended behavior - it might be intentionally designed this way to not "spoil" the next line - however it does seem odd.

Thank you so much for your work on this project, this is amazing!

**Comment by ILikeAI** [comment]
Good catch! All fixed now. Thanks for pointing that out :)
