### ISSUE TITLE
faster-whisper with multilingual

### ISSUE THREAD

**Issue by RailWar** [ILikeAI/AlwaysReddy#77]
There is new version of faster-whisper (but is has same version 1.0.3) on https://github.com/SYSTRAN/faster-whisper. It has a new parameter 'multilingual'. How can I update current package in vent/Lib/site-packages from sources?

**Comment by Jobus0** [comment]
To update faster-whisper, navigate to the AlwaysReddy folder in your terminal/console, then enter this:

Windows:
`venv\Scripts\python.exe -m pip install --upgrade faster-whisper`

Linux:
`venv\bin\python -m pip install --upgrade faster-whisper`

But just so you know, that new 'multilingual' parameter is specifically for when there are more than one language in a single recording.

If you just want to use Whisper in a different language than English, just set WHISPER_MODEL in your config.py to one of the multilingual models. The default is **tiny.en**. If you just remove the "**.en**" suffix, it will understand other languages too. Also no need to update the package for this.

For reference:

|  Size  | Parameters | English-only model | Multilingual model |
|:------:|:----------:|:------------------:|:------------------:|
|  tiny  |    39 M    |     `tiny.en`      |       `tiny` |
|  base  |    74 M    |     `base.en`      |       `base`  |
| small  |   244 M    |     `small.en`     |      `small`    |
| medium |   769 M    |    `medium.en`     |      `medium` |
| large  |   1550 M   |        N/A         |      `large`   |

**Comment by RailWar** [comment]
I want to try the network instead of an Italian teacher. My native language is Russian. When I speak Italian, even with the tiny or base model, it says that it is English.
I changed config.py and faster_whisper_client.py to specify the language. But it seems to me that using the multilingual parameter you can get better results.

**Comment by RailWar** [comment]
Unfortunately, upgrade faster-whisper installed the same version of the package. I would like it from https://github.com/SYSTRAN/faster-whisper

**Comment by RailWar** [comment]
however, I still don’t know if this version with two languages ​​will help me

**Comment by Jobus0** [comment]
### First remove the old version

Windows:
`venv\Scripts\python.exe -m pip uninstall faster-whisper`

Linux:
`venv\bin\python -m pip uninstall faster-whisper`

### Then install directly from the git repo

Windows:
`venv\Scripts\python.exe -m pip install git+https://github.com/SYSTRAN/faster-whisper.git`

Linux:
`venv\bin\python-m pip install git+https://github.com/SYSTRAN/faster-whisper.git`
