### ISSUE TITLE
Transcript:  Hello and good morning. Request failed with status code 400

### ISSUE THREAD

**Issue by ctxadm** [ILikeAI/AlwaysReddy#84]
Transcript:
 Hello and good morning.
Request failed with status code 400
Traceback (most recent call last):
  File "D:\AlwaysReddy\llm_apis\ollama_client.py", line 55, in stream_completion
    raise RuntimeError(f"Request failed with status code {response.status_code}")
RuntimeError: Request failed with status code 400
Traceback (most recent call last):
  File "D:\AlwaysReddy\llm_apis\ollama_client.py", line 55, in stream_completion
    raise RuntimeError(f"Request failed with status code {response.status_code}")
RuntimeError: Request failed with status code 400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AlwaysReddy\actions\always_reddy_voice_assistant\main.py", line 62, in handle_default_assistant_response
    response = self.AR.completion_client.process_text_stream(stream,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AlwaysReddy\completion_manager.py", line 166, in process_text_stream
    for chunk in text_stream:
  File "D:\AlwaysReddy\llm_apis\ollama_client.py", line 62, in stream_completion
    raise RuntimeError(f"An error occurred streaming completion from Ollama API: {e}")
RuntimeError: An error occurred streaming completion from Ollama API: Request failed with status code 400

iam not a coder, so maybe someone has an idea. 

Voice will be recorded, but the it runs into this error.

thanks in advice

**Comment by ctxadm** [comment]
forget to set USE_GPU = True

**Comment by ctxadm** [comment]
case closed

**Comment by Jobus0** [comment]
Last time I saw status code 400 from Ollama, it was because OLLAMA_KEEP_ALIVE in config.py was set to an invalid value. `USE_GPU` is not used by the completion APIs - it is currently only used by Whisper STT.

**Comment by ctxadm** [comment]
ok thanks for claryfing - thumbs up

**Comment by ILikeAI** [comment]
@ctxadm is this now resolved? :)

**Comment by ctxadm** [comment]
yes its solved! thanks!!!

**Comment by mrblaze27** [comment]
Hi, 
someone can help me?
same error with 405 code:
    raise RuntimeError(f"An error occurred streaming completion from Ollama API: {e}")
RuntimeError: An error occurred streaming completion from Ollama API: Request failed with status code 405

**Comment by Jobus0** [comment]
> Hi, someone can help me? same error with 405 code: raise RuntimeError(f"An error occurred streaming completion from Ollama API: {e}") RuntimeError: An error occurred streaming completion from Ollama API: Request failed with status code 405

Never seen 405 before. But that error is entirely different, so please open a new issue and include your Ollama-related config.py options.
