### ISSUE TITLE
some infos about -> Saving clipboard text...

### ISSUE THREAD

**Issue by ctxadm** [ILikeAI/AlwaysReddy#88]
when copy stuff from the clipboard to AlwaysReddy the Saving clipboard text... appears, if you dont interact with the CLI nothing happens anymore.

when u interact with "ctrl + alt + r", you can start a new recording (based on the clipboard stuff...

by the way, if you copy clipboard stuff with more the 1000+ signs, AlwaysReddy runs into an timeout

**Comment by Jobus0** [comment]
> when copy stuff from the clipboard to AlwaysReddy the Saving clipboard text... appears, if you dont interact with the CLI nothing happens anymore.

Seems like there is a misunderstanding. When you double-click the hotkey to give the assistant your clipboard content, it also starts listening for your voice at the same time - it's a two-in-one function.

So as a usage example:
1. You select and copy some text to the clipboard.
2. You double press the hotkey.
3. Speak into the mic what you want the assistant to do with the clipboard content.
4. Press the hotkey again to finish your input. The assistant will now receive both your recorded request and the clipboard content together.

> by the way, if you copy clipboard stuff with more the 1000+ signs, AlwaysReddy runs into an timeout

Hmm, try increasing the `MAX_TOKENS` option in your config.py.

If you're using Ollama, maybe also try adding the `"num_ctx"` (context window size) parameter to the `COMPLETION_PARAMS` list also in your config.py. This allows the model to keep more data in its memory. The default value for Ollama is 2048, which is relatively low, most models can go higher.

Example:
```py
COMPLETION_PARAMS = {"temperature": 0.7, "max_tokens": 2048, "num_ctx": 4096}
```
